In [3]:
import json
import pandas as pd
import polars as pl
import os
from tqdm import tqdm

In [4]:
META_DIR = '/home/dangnh36/datasets/.comp/byu/external/meta/'

tomo_ids = sorted([e.replace('.json', '') for e in os.listdir(META_DIR)])
print(len(tomo_ids))
print(tomo_ids[:5])

1287
['aba2013-04-06-10', 'aba2013-04-06-12', 'aba2013-04-06-13', 'aba2013-04-06-14', 'aba2013-04-06-15']

In [5]:
all_metas = []
for tomo_id in tqdm(tomo_ids):
    meta_path = os.path.join(META_DIR, f'{tomo_id}.json')
    try:
        with open(meta_path, 'rb') as f:
            meta = json.load(f)
            all_metas.append(meta)
    except:
        print(tomo_id)
        break
len(all_metas)

100%|█████████| 1287/1287 [00:03<00:00, 328.89it/s]

1287

In [6]:
df = pd.DataFrame(all_metas)
df

,tomo_id,ori_spacing,PORTAL__alignment_id,PORTAL__ctf_corrected,PORTAL__deposition_id,PORTAL__fiducial_alignment_status,PORTAL__https_mrc_file,PORTAL__https_omezarr_dir,PORTAL__id,PORTAL__is_author_submitted,...,ori_dtype,ori_histogram,ori_histogram_bins,ori_tomo_min,ori_tomo_max,ori_tomo_mean,ori_tomo_std,detected_as_uint8_range,target_spacing,target_shape
0,aba2013-04-06-10,10.829,13562,False,10054,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,13562,True,...,float32,"[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,24.154366,2.952390,True,16.000,"[541, 625, 647]"
1,aba2013-04-06-12,10.829,13564,False,10054,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,13564,True,...,float32,"[1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,42.995575,4.758522,True,16.000,"[541, 625, 647]"
2,aba2013-04-06-13,10.829,13565,False,10054,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,13565,True,...,float32,"[1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,40.527657,5.222191,True,16.000,"[541, 625, 647]"
3,aba2013-04-06-14,10.829,13566,False,10054,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,13566,True,...,float32,"[1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,48.713768,4.632757,True,16.000,"[541, 625, 647]"
4,aba2013-04-06-15,10.829,13567,False,10054,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,13567,True,...,float32,"[1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,45.733704,5.384742,True,16.000,"[541, 625, 647]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,ycw2013-11-24-19,19.733,12336,False,10017,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,12336,True,...,float32,"[1, 1, 0, 0, 1, 0, 2, 2, 3, 0, 0, 3, 2, 3, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,23.346630,4.913575,True,19.733,"[800, 928, 960]"
1283,ycw2013-11-24-2,19.733,12337,False,10017,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,12337,True,...,float32,"[1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 1, 2, 1, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,21.911663,5.232660,True,19.733,"[800, 928, 960]"
1284,ycw2013-11-24-24,19.733,12342,False,10017,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,12342,True,...,float32,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,37.145935,4.875950,True,19.733,"[800, 928, 960]"
1285,ycw2013-11-24-5,19.733,12345,False,10017,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,12345,True,...,float32,"[1, 1, 1, 1, 2, 0, 1, 0, 3, 1, 1, 4, 1, 2, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,26.328320,4.593496,True,19.733,"[800, 928, 960]"
1286,ycw2017-11-30-30,16.145,8643,False,10056,FIDUCIAL,https://files.cryoetdataportal.cziscience.com/...,https://files.cryoetdataportal.cziscience.com/...,8643,True,...,float32,"[1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,19.454260,3.170272,True,16.145,"[600, 928, 960]"

In [7]:
df.at[0, 'target_shape'][0]

541

In [8]:
df['Z'] = df['target_shape'].apply(lambda x: x[0])
df['Y'] = df['target_shape'].apply(lambda x: x[1])
df['X'] = df['target_shape'].apply(lambda x: x[2])

In [9]:
list(df.columns)

['tomo_id',
 'ori_spacing',
 'PORTAL__alignment_id',
 'PORTAL__ctf_corrected',
 'PORTAL__deposition_id',
 'PORTAL__fiducial_alignment_status',
 'PORTAL__https_mrc_file',
 'PORTAL__https_omezarr_dir',
 'PORTAL__id',
 'PORTAL__is_author_submitted',
 'PORTAL__is_portal_standard',
 'PORTAL__is_visualization_default',
 'PORTAL__key_photo_thumbnail_url',
 'PORTAL__key_photo_url',
 'PORTAL__name',
 'PORTAL__neuroglancer_config',
 'PORTAL__offset_x',
 'PORTAL__offset_y',
 'PORTAL__offset_z',
 'PORTAL__processing',
 'PORTAL__processing_software',
 'PORTAL__publications',
 'PORTAL__reconstruction_method',
 'PORTAL__reconstruction_software',
 'PORTAL__related_database_entries',
 'PORTAL__run_id',
 'PORTAL__s3_mrc_file',
 'PORTAL__s3_omezarr_dir',
 'PORTAL__scale_0_dimensions',
 'PORTAL__scale_1_dimensions',
 'PORTAL__scale_2_dimensions',
 'PORTAL__size_x',
 'PORTAL__size_y',
 'PORTAL__size_z',
 'PORTAL__tomogram_version',
 'PORTAL__tomogram_voxel_spacing_id',
 'PORTAL__voxel_spacing',
 'ori_shape',
 'ori_dtype',
 'ori_histogram',
 'ori_histogram_bins',
 'ori_tomo_min',
 'ori_tomo_max',
 'ori_tomo_mean',
 'ori_tomo_std',
 'detected_as_uint8_range',
 'target_spacing',
 'target_shape',
 'Z',
 'Y',
 'X']

In [10]:
df = df[
['tomo_id',
 'ori_spacing',
 'ori_shape',
 'ori_dtype',
 'detected_as_uint8_range',
 'target_spacing',
 'target_shape',
 'Z',
 'Y',
 'X',
 'PORTAL__alignment_id',
 'PORTAL__ctf_corrected',
 'PORTAL__deposition_id',
 'PORTAL__fiducial_alignment_status',
 'PORTAL__https_mrc_file',
 'PORTAL__https_omezarr_dir',
 'PORTAL__id',
 'PORTAL__is_author_submitted',
 'PORTAL__is_portal_standard',
 'PORTAL__is_visualization_default',
 'PORTAL__key_photo_thumbnail_url',
 'PORTAL__key_photo_url',
 'PORTAL__name',
 'PORTAL__neuroglancer_config',
 'PORTAL__offset_x',
 'PORTAL__offset_y',
 'PORTAL__offset_z',
 'PORTAL__processing',
 'PORTAL__processing_software',
 'PORTAL__publications',
 'PORTAL__reconstruction_method',
 'PORTAL__reconstruction_software',
 'PORTAL__related_database_entries',
 'PORTAL__run_id',
 'PORTAL__s3_mrc_file',
 'PORTAL__s3_omezarr_dir',
 'PORTAL__scale_0_dimensions',
 'PORTAL__scale_1_dimensions',
 'PORTAL__scale_2_dimensions',
 'PORTAL__size_x',
 'PORTAL__size_y',
 'PORTAL__size_z',
 'PORTAL__tomogram_version',
 'PORTAL__tomogram_voxel_spacing_id',
 'PORTAL__voxel_spacing',
 'ori_histogram',
 'ori_histogram_bins',
 'ori_tomo_min',
 'ori_tomo_max',
 'ori_tomo_mean',
 'ori_tomo_std',
 ]
]

In [11]:
df

,tomo_id,ori_spacing,ori_shape,ori_dtype,detected_as_uint8_range,target_spacing,target_shape,Z,Y,X,...,PORTAL__size_z,PORTAL__tomogram_version,PORTAL__tomogram_voxel_spacing_id,PORTAL__voxel_spacing,ori_histogram,ori_histogram_bins,ori_tomo_min,ori_tomo_max,ori_tomo_mean,ori_tomo_std
0,aba2013-04-06-10,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13442,10.829,"[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,24.154366,2.952390
1,aba2013-04-06-12,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13444,10.829,"[1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,42.995575,4.758522
2,aba2013-04-06-13,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13445,10.829,"[1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,40.527657,5.222191
3,aba2013-04-06-14,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13446,10.829,"[1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,48.713768,4.632757
4,aba2013-04-06-15,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13447,10.829,"[1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,45.733704,5.384742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,ycw2013-11-24-19,19.733,"[800, 928, 960]",float32,True,19.733,"[800, 928, 960]",800,928,960,...,800,1.0,12216,19.733,"[1, 1, 0, 0, 1, 0, 2, 2, 3, 0, 0, 3, 2, 3, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,23.346630,4.913575
1283,ycw2013-11-24-2,19.733,"[800, 928, 960]",float32,True,19.733,"[800, 928, 960]",800,928,960,...,800,1.0,12217,19.733,"[1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 1, 2, 1, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,21.911663,5.232660
1284,ycw2013-11-24-24,19.733,"[800, 928, 960]",float32,True,19.733,"[800, 928, 960]",800,928,960,...,800,1.0,12222,19.733,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,37.145935,4.875950
1285,ycw2013-11-24-5,19.733,"[800, 928, 960]",float32,True,19.733,"[800, 928, 960]",800,928,960,...,800,1.0,12225,19.733,"[1, 1, 1, 1, 2, 0, 1, 0, 3, 1, 1, 4, 1, 2, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,26.328320,4.593496
1286,ycw2017-11-30-30,16.145,"[600, 928, 960]",float32,True,16.145,"[600, 928, 960]",600,928,960,...,600,1.0,8523,16.145,"[1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,19.454260,3.170272

In [12]:
df['detected_as_uint8_range'].mean()

0.9712509712509713

In [13]:
df[df['detected_as_uint8_range']].sample(5)

,tomo_id,ori_spacing,ori_shape,ori_dtype,detected_as_uint8_range,target_spacing,target_shape,Z,Y,X,...,PORTAL__size_z,PORTAL__tomogram_version,PORTAL__tomogram_voxel_spacing_id,PORTAL__voxel_spacing,ori_histogram,ori_histogram_bins,ori_tomo_min,ori_tomo_max,ori_tomo_mean,ori_tomo_std
246,aba2015-06-03-26,13.236,"[800, 928, 928]",float32,True,16.0,"[661, 767, 767]",661,767,767,...,800,1.0,11527,13.236,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,31.552914,3.382599
591,mba2011-03-25-3,6.320,"[500, 2048, 2048]",float32,True,16.0,"[197, 808, 808]",197,808,808,...,500,1.0,10415,6.320,"[1, 1, 6, 3, 5, 4, 12, 8, 7, 5, 11, 10, 10, 13...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,37.398514,6.100639
565,mba2011-03-02-2,7.740,"[570, 2048, 2048]",float32,True,16.0,"[275, 990, 990]",275,990,990,...,570,1.0,16120,7.740,"[4, 5, 7, 6, 8, 10, 13, 11, 11, 12, 11, 16, 13...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,29.100483,5.204069
297,aba2015-07-15-59,13.059,"[800, 928, 960]",float32,True,16.0,"[652, 757, 783]",652,757,783,...,800,1.0,11655,13.059,"[1, 1, 0, 3, 1, 0, 1, 2, 2, 2, 4, 0, 4, 1, 1, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,35.929142,3.674479
169,aba2015-01-16-17,13.059,"[800, 928, 960]",float32,True,16.0,"[652, 757, 783]",652,757,783,...,800,1.0,11546,13.059,"[1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 1, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,34.161350,6.569161

In [ ]:
df.to_csv('/home/dangnh36/datasets/.comp/byu/processed/external/metadata_full.csv', index = False)

In [15]:
df = pd.read_csv('/home/dangnh36/datasets/.comp/byu/external/metadata_full.csv')
df

,tomo_id,ori_spacing,ori_shape,ori_dtype,detected_as_uint8_range,target_spacing,target_shape,Z,Y,X,...,PORTAL__size_z,PORTAL__tomogram_version,PORTAL__tomogram_voxel_spacing_id,PORTAL__voxel_spacing,ori_histogram,ori_histogram_bins,ori_tomo_min,ori_tomo_max,ori_tomo_mean,ori_tomo_std
0,aba2013-04-06-10,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13442,10.829,"[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,24.154366,2.952390
1,aba2013-04-06-12,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13444,10.829,"[1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,42.995575,4.758522
2,aba2013-04-06-13,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13445,10.829,"[1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,40.527657,5.222191
3,aba2013-04-06-14,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13446,10.829,"[1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,48.713768,4.632757
4,aba2013-04-06-15,10.829,"[800, 924, 956]",float32,True,16.000,"[541, 625, 647]",541,625,647,...,800,1.0,13447,10.829,"[1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,45.733704,5.384742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,ycw2013-11-24-19,19.733,"[800, 928, 960]",float32,True,19.733,"[800, 928, 960]",800,928,960,...,800,1.0,12216,19.733,"[1, 1, 0, 0, 1, 0, 2, 2, 3, 0, 0, 3, 2, 3, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,23.346630,4.913575
1283,ycw2013-11-24-2,19.733,"[800, 928, 960]",float32,True,19.733,"[800, 928, 960]",800,928,960,...,800,1.0,12217,19.733,"[1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 1, 2, 1, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,21.911663,5.232660
1284,ycw2013-11-24-24,19.733,"[800, 928, 960]",float32,True,19.733,"[800, 928, 960]",800,928,960,...,800,1.0,12222,19.733,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,37.145935,4.875950
1285,ycw2013-11-24-5,19.733,"[800, 928, 960]",float32,True,19.733,"[800, 928, 960]",800,928,960,...,800,1.0,12225,19.733,"[1, 1, 1, 1, 2, 0, 1, 0, 3, 1, 1, 4, 1, 2, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,26.328320,4.593496
1286,ycw2017-11-30-30,16.145,"[600, 928, 960]",float32,True,16.145,"[600, 928, 960]",600,928,960,...,600,1.0,8523,16.145,"[1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,19.454260,3.170272

In [16]:
print(df['Z'].median(), df['Y'].median(), df['X'].median())
print(df['Z'].mean(), df['Y'].mean(), df['X'].mean())
print(df['Z'].std(), df['Y'].std(), df['X'].std())

256.0 646.0 650.0
362.72727272727275 550.4887334887335 566.3729603729604
229.83502987702911 272.5632998042532 276.2445793772605

In [17]:
TOMO_DIR = '/home/dangnh36/datasets/.comp/byu/external/tomogram/'
import cv2

for i, row in tqdm(df.iterrows()):
    tomo_id = row['tomo_id']
    Z = row['Z']
    Y = row['Y']
    X = row['X']
    tomo_dir = os.path.join(TOMO_DIR, tomo_id)
    fnames = os.listdir(tomo_dir)
    # assert len(fnames) == Z, f'{tomo_id} {len(fnames)} {Z}'
    if len(fnames) != Z:
        print(f'{tomo_id} {len(fnames)} {Z}')
        
    img = cv2.imread(os.path.join(TOMO_DIR, tomo_id, fnames[0]))
    assert img.shape[:2] == (Y, X)

1287it [00:11, 108.70it/s]

In [20]:
label_df = pd.read_csv('/home/dangnh36/datasets/.comp/byu/external/brendanartley_external_labels.csv')
label_df

         z           y           x           tomo_id  dataset_id
0     67.0  191.170202  345.324574  aba2013-04-06-10       10287
1     68.0  187.612793  229.115898  aba2013-04-06-12       10287
2     64.0  481.098988  228.522997  aba2013-04-06-13       10287
3     61.0  146.702596  236.823617  aba2013-04-06-14       10287
4     69.0   83.855048  398.092798  aba2013-04-06-15       10287
...    ...         ...         ...               ...         ...
1612  74.0  157.066058  411.903802   ycw2013-11-24-5       10139
1613  75.0  167.971277  429.122568   ycw2013-11-24-5       10139
1614  64.0   65.232640  314.330794   ycw2013-11-24-5       10139
1615  78.0  122.851181  334.876073  ycw2017-11-30-30       10168
1616  78.0  152.599194  332.027859  ycw2017-11-30-30       10168

[1617 rows x 5 columns]

In [21]:
label_df = label_df.merge(df, on = 'tomo_id', how = 'left', validate = "m:1")
label_df

,z,y,x,tomo_id,dataset_id,ori_spacing,ori_shape,ori_dtype,detected_as_uint8_range,target_spacing,...,PORTAL__size_z,PORTAL__tomogram_version,PORTAL__tomogram_voxel_spacing_id,PORTAL__voxel_spacing,ori_histogram,ori_histogram_bins,ori_tomo_min,ori_tomo_max,ori_tomo_mean,ori_tomo_std
0,67.0,191.170202,345.324574,aba2013-04-06-10,10287,10.829,"[800, 924, 956]",float32,True,16.000,...,800.0,1.0,13442.0,10.829,"[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,24.154366,2.952390
1,68.0,187.612793,229.115898,aba2013-04-06-12,10287,10.829,"[800, 924, 956]",float32,True,16.000,...,800.0,1.0,13444.0,10.829,"[1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,42.995575,4.758522
2,64.0,481.098988,228.522997,aba2013-04-06-13,10287,10.829,"[800, 924, 956]",float32,True,16.000,...,800.0,1.0,13445.0,10.829,"[1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,40.527657,5.222191
3,61.0,146.702596,236.823617,aba2013-04-06-14,10287,10.829,"[800, 924, 956]",float32,True,16.000,...,800.0,1.0,13446.0,10.829,"[1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,48.713768,4.632757
4,69.0,83.855048,398.092798,aba2013-04-06-15,10287,10.829,"[800, 924, 956]",float32,True,16.000,...,800.0,1.0,13447.0,10.829,"[1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,45.733704,5.384742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,74.0,157.066058,411.903802,ycw2013-11-24-5,10139,19.733,"[800, 928, 960]",float32,True,19.733,...,800.0,1.0,12225.0,19.733,"[1, 1, 1, 1, 2, 0, 1, 0, 3, 1, 1, 4, 1, 2, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,26.328320,4.593496
1613,75.0,167.971277,429.122568,ycw2013-11-24-5,10139,19.733,"[800, 928, 960]",float32,True,19.733,...,800.0,1.0,12225.0,19.733,"[1, 1, 1, 1, 2, 0, 1, 0, 3, 1, 1, 4, 1, 2, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,26.328320,4.593496
1614,64.0,65.232640,314.330794,ycw2013-11-24-5,10139,19.733,"[800, 928, 960]",float32,True,19.733,...,800.0,1.0,12225.0,19.733,"[1, 1, 1, 1, 2, 0, 1, 0, 3, 1, 1, 4, 1, 2, 0, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,26.328320,4.593496
1615,78.0,122.851181,334.876073,ycw2017-11-30-30,10168,16.145,"[600, 928, 960]",float32,True,16.145,...,600.0,1.0,8523.0,16.145,"[1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,19.454260,3.170272
1616,78.0,152.599194,332.027859,ycw2017-11-30-30,10168,16.145,"[600, 928, 960]",float32,True,16.145,...,600.0,1.0,8523.0,16.145,"[1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 2, ...","[-128.0, -127.00390625, -126.0078125, -125.011...",-128.0,127.0,19.454260,3.170272

In [22]:
set(label_df['tomo_id']).difference(set(df['tomo_id']))

{'mba2011-07-18-1'}

In [ ]:
# !rm -rf /home/dangnh36/datasets/.comp/byu/processed/viz/external_annotations/

In [25]:
ALL_TOMO_IDS = label_df['tomo_id'].unique().tolist()
len(ALL_TOMO_IDS)

1288

In [31]:
[e for e in ALL_TOMO_IDS if e.startswith('tomo_')]

[]

In [28]:
_tmp_df = pd.read_csv('/home/dangnh36/datasets/.comp/byu/processed/gt_v2.csv')
_tmp_df

,tomo_id,Z,Y,X,voxel_spacing,ori_num_motors,num_motors,ZA,YA,XA,V,VA,motor_z,motor_y,motor_x,motor_zA,motor_yA,motor_xA,motor_zyx,motor_zyxA
0,tomo_003acc,500,1912,1847,6.5,0,0,3250.0,12428.0,12005.5,1765732000,4.849142e+11,-1.00,-1.0,-1.0,-6.500,-6.50,-6.5,[],[]
1,tomo_00e047,300,959,928,15.6,1,1,4680.0,14960.4,14476.8,266985600,1.013588e+12,169.00,546.0,603.0,2636.400,8517.60,9406.8,"[[169.0, 546.0, 603.0]]","[[2636.4, 8517.6, 9406.8]]"
2,tomo_00e463,500,924,956,19.7,6,6,9850.0,18202.8,18833.2,441672000,3.376747e+12,235.00,403.0,137.0,4629.500,7939.10,2698.9,"[[235.0, 403.0, 137.0], [243.0, 363.0, 153.0],...","[[4629.5, 7939.099999999999, 2698.9], [4787.09..."
3,tomo_01a877,300,960,928,13.1,1,1,3930.0,12576.0,12156.8,267264000,6.008338e+11,147.00,638.0,286.0,1925.700,8357.80,3746.6,"[[147.0, 638.0, 286.0]]","[[1925.7, 8357.8, 3746.6]]"
4,tomo_02862f,300,959,928,15.6,1,1,4680.0,14960.4,14476.8,266985600,1.013588e+12,101.00,351.0,120.0,1575.600,5475.60,1872.0,"[[101.0, 351.0, 120.0]]","[[1575.6, 5475.599999999999, 1872.0]]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,tomo_fe050c,300,959,928,15.6,1,2,4680.0,14960.4,14476.8,266985600,1.013588e+12,138.00,134.0,542.0,2152.800,2090.40,8455.2,"[[138.0, 134.0, 542.0], [143.125, 93.875, 405....","[[2152.7999999999997, 2090.4, 8455.19999999999..."
644,tomo_fe85f6,800,928,960,13.1,0,1,10480.0,12156.8,12576.0,712704000,1.602223e+12,463.50,903.5,747.0,6071.850,11835.85,9785.7,"[[463.5, 903.5, 747.0]]","[[6071.849999999999, 11835.85, 9785.6999999999..."
645,tomo_fea6e8,300,960,928,16.8,0,0,5040.0,16128.0,15590.4,267264000,1.267268e+12,-1.00,-1.0,-1.0,-16.800,-16.80,-16.8,[],[]
646,tomo_ff505c,300,959,928,15.6,1,1,4680.0,14960.4,14476.8,266985600,1.013588e+12,111.00,816.0,678.0,1731.600,12729.60,10576.8,"[[111.0, 816.0, 678.0]]","[[1731.6, 12729.6, 10576.8]]"
647,tomo_ff7c20,800,928,960,13.1,0,1,10480.0,12156.8,12576.0,712704000,1.602223e+12,307.25,493.0,63.0,4024.975,6458.30,825.3,"[[307.25, 493.0, 63.0]]","[[4024.975, 6458.3, 825.3]]"

In [29]:
_byu_tomo_ids = _tmp_df['tomo_id'].unique().tolist()
len(_byu_tomo_ids)

648

In [30]:
len([e for e in _byu_tomo_ids if e.startswith('tomo_')])

648

In [24]:
import numpy as np

all_target_z = []
all_target_y = []
all_target_x = []

SAVE_VIZ_DIR = '/home/dangnh36/datasets/.comp/byu/processed/viz/external_annotations_per_dataset/'

os.makedirs(SAVE_VIZ_DIR, exist_ok=True)

for i, row in tqdm(label_df.iterrows()):
    tomo_id = row['tomo_id']
    if tomo_id == 'mba2011-07-18-1':
        all_target_z.append(-1)
        all_target_y.append(-1)
        all_target_x.append(-1)
        continue
    Z, Y, X = eval(row['target_shape'])
    ori_Z, ori_Y, ori_X = eval(row['ori_shape'])
    z_indices = np.linspace(0, ori_Z-1, 128).astype(int)
    assert len(z_indices) == 128
    z = row['z']
    assert z == int(z)
    z = int(z)
    ori_z = z_indices[z]
    target_z = (ori_z + 0.5) * Z / ori_Z - 0.5
    target_y = (row['y'] + 0.5) / 512. * Y - 0.5
    target_x = (row['x'] + 0.5) / 512. * X - 0.5
    all_target_z.append(target_z)
    all_target_y.append(target_y)
    all_target_x.append(target_x)

    img = cv2.imread(os.path.join(TOMO_DIR, tomo_id, f'slice_{round(target_z):04d}.jpg'))
    radius = round(1000. / row['target_spacing'])
    cv2.circle(
        img,                    # Image
        center=(round(target_x), round(target_y)),      # (x, y) center coordinates
        radius=radius,              # Radius of the circle
        color=(0, 255, 0),      # Color in BGR (green)
        thickness=2             # Thickness (-1 to fill the circle)
    )
    save_path = os.path.join(SAVE_VIZ_DIR, str(row['dataset_id']), f'{i}__{tomo_id}.jpg')
    os.makedirs(os.path.dirname(save_path), exist_ok = True)
    cv2.imwrite(save_path, img)

1617it [00:20, 78.55it/s]

In [ ]:
len(label_df), len(all_target_z), len(all_target_y), len(all_target_x)

In [ ]:
label_df['motor_z'] = all_target_z
label_df['motor_y'] = all_target_y
label_df['motor_x'] = all_target_x
label_df

In [ ]:
label_df = label_df.rename(columns = {'z': 'old_z', 'y': 'old_y', 'x': 'old_x'})

In [ ]:
label_df.columns

In [ ]:
label_df = label_df[
['motor_z', 'motor_y', 'motor_x', 'tomo_id', 'Z', 'Y', 'X', 'ori_spacing', 'ori_shape',
       'ori_dtype', 'target_spacing',
       'target_shape', 'detected_as_uint8_range', 'dataset_id', 'PORTAL__alignment_id',
       'PORTAL__ctf_corrected', 'PORTAL__deposition_id',
       'PORTAL__fiducial_alignment_status', 'PORTAL__https_mrc_file',
       'PORTAL__https_omezarr_dir', 'PORTAL__id',
       'PORTAL__is_author_submitted', 'PORTAL__is_portal_standard',
       'PORTAL__is_visualization_default', 'PORTAL__key_photo_thumbnail_url',
       'PORTAL__key_photo_url', 'PORTAL__name', 'PORTAL__neuroglancer_config',
       'PORTAL__offset_x', 'PORTAL__offset_y', 'PORTAL__offset_z',
       'PORTAL__processing', 'PORTAL__processing_software',
       'PORTAL__publications', 'PORTAL__reconstruction_method',
       'PORTAL__reconstruction_software', 'PORTAL__related_database_entries',
       'PORTAL__run_id', 'PORTAL__s3_mrc_file', 'PORTAL__s3_omezarr_dir',
       'PORTAL__scale_0_dimensions', 'PORTAL__scale_1_dimensions',
       'PORTAL__scale_2_dimensions', 'PORTAL__size_x', 'PORTAL__size_y',
       'PORTAL__size_z', 'PORTAL__tomogram_version',
       'PORTAL__tomogram_voxel_spacing_id', 'PORTAL__voxel_spacing',
       'ori_histogram', 'ori_histogram_bins', 'ori_tomo_min', 'ori_tomo_max',
       'ori_tomo_mean', 'ori_tomo_std', 'old_z', 'old_y', 'old_x']
]
label_df

In [ ]:
display(label_df[label_df['motor_z'] > label_df['Z'] - 1])
display(label_df[label_df['motor_y'] > label_df['Y'] - 1])
display(label_df[label_df['motor_x'] > label_df['X'] - 1])

In [ ]:
(label_df['motor_z'] > label_df['Z'] - 1).any()

In [ ]:
(label_df['motor_z'] <= (label_df['Z'] - 1)).all()

In [ ]:
tmp = (label_df['motor_z'] < (label_df['Z'] - 1)).tolist()
for i, e in enumerate(tmp):
    if not e:
        print(i, e)

In [ ]:
label_df = label_df[label_df['tomo_id'] != 'mba2011-07-18-1'].reset_index(drop = True)
label_df

In [ ]:
label_df['motor_z'].min(), label_df['motor_y'].min(), label_df['motor_x'].min()

In [ ]:
label_df.to_csv('/home/dangnh36/datasets/.comp/byu/processed/external_labels_v1.csv', index = False)

In [ ]:
df[df['tomo_id'] == 'mba2012-01-02-11']

In [ ]:
df.columns

In [ ]:
MAIN_COLS = ['tomo_id', 'ori_spacing', 'ori_shape', 'ori_dtype', 'detected_as_uint8_bug', 'target_spacing', 'target_shape', 'Z', 'Y', 'X']

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
print(df[df['ori_tomo_min'] >= 0]['tomo_id'].count(), df[df['ori_tomo_min'] < 0]['tomo_id'].count())
df[df['ori_tomo_min'] >=0].sample(5)

In [ ]:
viz_names = os.listdir(SAVE_VIZ_DIR)


for tomo_id in ['mba2012-08-29-8', 'mba2012-09-19-16', 'aba2013-04-06-15', 'mba2010-09-09-2', 'mba2011-03-24-10', 'aba2015-01-16-7', 'mba2011-04-12-1', 'mba2011-08-26-23', 'mba2011-11-23-15', 'mba2011-11-23-4']:
    tmp = df.loc[df['tomo_id'] == tomo_id, :].reset_index(drop=True)
    display(tmp)
    print(eval(tmp.at[0, 'ori_histogram_bins'])[:10], eval(tmp.at[0, 'ori_histogram_bins'])[-10:])
    print(eval(tmp.at[0, 'ori_histogram'])[:10], eval(tmp.at[0, 'ori_histogram'])[-10:])
    plt.bar(eval(tmp.at[0, 'ori_histogram_bins'])[:-1], eval(tmp.at[0, 'ori_histogram']))
    plt.show()
    fname = [e for e in viz_names if tomo_id in e][0]
    fpath = os.path.join(SAVE_VIZ_DIR, fname)
    img = cv2.imread(fpath)
    # img += 127

    new_hist, new_bins = np.histogram(img.flatten(), 256)
    plt.bar(new_bins[:-1], new_hist)
    plt.show()
    new_hist = new_hist / new_hist.sum() * 100.0
    print('PERCENTILE:', new_hist[0], new_hist[-1])
    print("STATS:", img.min(), img.mean(), img.max())
    
    plt.imshow(img)
    plt.show()
    print('--------------------------\n\n')